# Generated by Django 5.2.6 on 2025-09-24 05:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upgrade', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SimulationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_horsepower', models.FloatField()),
                ('new_torque', models.FloatField()),
                ('new_efficiency', models.FloatField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('upgrade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='upgrade.upgrade')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='upgrade.vehicle')),
            ],
        ),
    ]
