# Generated by Django 5.2.6 on 2025-10-08 05:24

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upgrade', '0003_profile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='simulationresult',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 10, 8, 5, 23, 38, 707312, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehicle',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='simulationresult',
            name='new_horsepower',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='simulationresult',
            name='new_torque',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='base_hp',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='base_torque',
            field=models.IntegerField(default=150),
        ),
    ]
