# Generated by Django 5.2.6 on 2025-10-08 05:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upgrade', '0004_simulationresult_created_at_vehicle_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simulationresult',
            name='upgrade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='upgrade.upgrade'),
        ),
    ]
